#!/system/bin/sh

SCRIPT_PATH=$(readlink -f $0)
. ${SCRIPT_PATH%/*}/bootkali_log
. ${SCRIPT_PATH%/*}/bootkali_env

## Validate busybox path.
if [ -z "$BUSYBOX" ]; then
    bklog "[-] No busybox_nh is installed or busybox is not granted execute permission, if you did have it installed, please symlink it to /system/bin and grant it the permission."
    exit 1
fi

if [ ! -d "$MNT" ]; then
    bklog "[-] \"$MNT\" directory does not exist!"
    bklog "[!] Click the button [INSTALL KALI CHROOT] below next!"
    exit 2
fi

# Goals:
# 01. Check mountpoints
# 02. Mount them to the chroot
# 03 . Looking for any issues
# 04. returns 0